
[folders]
csv_data_path="/home/steve/Data/MDR source data/ANZCTR"
json_data_path="/home/steve/Data/MDR json files/anz"
log_folder_path="/home/steve/Data/MDR/MDR_Logs/anz"

[database]
db_host="localhost"
db_user="postgres"
db_password="WinterIsComing!"
db_port="5432"
mon_db_name="mon"
src_db_name="anz"


